import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { describe, it } from "node:test";
import { createHttpTransport } from "../../src/features/assistant/adapters/http.ts";
import {
  readSse,
  StreamProtocolError,
  StreamStalledError,
} from "../../src/features/assistant/adapters/sse.ts";
import { AssistantError } from "../../src/features/assistant/application/ports.ts";
import type { RunEvent } from "../../src/features/assistant/domain/models.ts";

/** Real examples generated by the API (contracts/api, pinned in contracts/source.json). */
const example = (name: string) =>
  readFileSync(new URL(`../../contracts/api/examples/${name}`, import.meta.url), "utf8");
const session = JSON.parse(example("session.created.json")) as unknown;
const STREAMS = [
  "stream.recommendation.sse",
  "stream.price-unverified.sse",
  "stream.answer-replaced.sse",
  "stream.unknown-policy.sse",
  "stream.payment-data-refused.sse",
  "stream.failed.sse",
  "stream.cancelled.sse",
];
/** Decoded events of an example, for building malformed variants. */
const events = (name: string): Record<string, unknown>[] =>
  example(name)
    .split(/\n\n/)
    .map((frame) => frame.split("\n").find((line) => line.startsWith("data:")))
    .filter((line): line is string => Boolean(line))
    .map((line) => JSON.parse(line.slice(5)) as Record<string, unknown>);

const encode = (list: unknown[]) =>
  list
    .map((event) => {
      const e = event as { type: string; sequence: number };
      return `id: ${e.sequence}\nevent: ${e.type}\ndata: ${JSON.stringify(event)}\n\n`;
    })
    .join("");

function stream(text: string, chunk = 7): ReadableStream<Uint8Array> {
  const bytes = new TextEncoder().encode(text);
  let offset = 0;
  return new ReadableStream({
    pull(controller) {
      if (offset >= bytes.length) return controller.close();
      controller.enqueue(bytes.slice(offset, offset + chunk));
      offset += chunk;
    },
  });
}

const sse = (text: string, init: ResponseInit = {}) =>
  new Response(stream(text), {
    status: 200,
    headers: { "content-type": "text/event-stream" },
    ...init,
  });
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });

describe("SSE reader", () => {
  it("accepts every example stream the API publishes, in 1-byte and 7-byte chunks", async () => {
    for (const name of STREAMS)
      for (const size of [1, 7]) {
        const types: string[] = [];
        const terminal = await readSse(stream(example(name), size), (event) =>
          types.push(event.type),
        );
        assert.equal(terminal, true, name);
        assert.ok(
          ["run.completed", "run.failed", "run.cancelled"].includes(types.at(-1) ?? ""),
          name,
        );
      }
  });

  it("maps the recommendation example to a verified product with purchase URL", async () => {
    let answer: unknown = null;
    await readSse(stream(example("stream.recommendation.sse")), (event) => {
      if (event.type === "message.completed") answer = event.message;
    });
    const message = answer as {
      products: { purchaseUrl: string; price: unknown }[];
      followUps: string[];
    };
    assert.ok(message.products.length >= 1);
    assert.match(message.products[0]?.purchaseUrl ?? "", /^https:\/\/pequeverso\.com\//);
    assert.ok(message.products[0]?.price, "a verified price is present in this example");
  });

  it("keeps price null when the API cannot confirm it", async () => {
    let prices: unknown[] = [];
    await readSse(stream(example("stream.price-unverified.sse")), (event) => {
      if (event.type === "message.completed") prices = event.message.products.map((p) => p.price);
    });
    assert.ok(prices.length > 0 && prices.every((price) => price === null));
  });

  it("ignores keep-alive comments and handles split UTF-8 code points", async () => {
    const texts: string[] = [];
    await readSse(stream(`: keep-alive\n\n${example("stream.recommendation.sse")}`, 1), (event) => {
      if (event.type === "message.delta") texts.push(event.text);
    });
    assert.match(texts.join(""), /años/);
  });

  it("rejects out-of-order sequences, run id changes, unknown fields and unknown types", async () => {
    const [started, delta] = events("stream.recommendation.sse");
    const cases = [
      encode([started, { ...delta, sequence: 0 }]),
      encode([started, { ...delta, run_id: "other" }]),
      encode([started, { ...delta, injected: "<script>" }]),
      "event: message.delta\ndata: {not json}\n\n",
      encode([{ ...started, type: "run.status" }]),
    ];
    for (const text of cases)
      await assert.rejects(
        readSse(stream(text), () => {}),
        StreamProtocolError,
      );
  });

  it("stops at the terminal event: trailing frames are never delivered", async () => {
    const [, delta] = events("stream.recommendation.sse");
    const types: string[] = [];
    await readSse(
      stream(`${example("stream.failed.sse")}${encode([{ ...delta, sequence: 99 }])}`),
      (event) => types.push(event.type),
    );
    assert.equal(types.at(-1), "run.failed");
    assert.ok(!types.slice(0, -1).includes("run.failed"));
  });

  it("reports EOF without a terminal event as not terminal", async () => {
    const [started, delta] = events("stream.recommendation.sse");
    assert.equal(await readSse(stream(encode([started, delta])), () => {}), false);
  });

  it("fails a stalled stream after the idle window instead of waiting forever", async () => {
    const [started] = events("stream.recommendation.sse");
    let sent = false;
    const stalled = new ReadableStream<Uint8Array>({
      pull(controller): Promise<void> {
        if (sent) return new Promise(() => {}); // never resolves: the connection went silent
        sent = true;
        controller.enqueue(new TextEncoder().encode(encode([started])));
        return Promise.resolve();
      },
    });
    await assert.rejects(
      readSse(stalled, () => {}, undefined, 50),
      StreamStalledError,
    );
  });

  it("stops reading when aborted", async () => {
    const controller = new AbortController();
    const never = new ReadableStream<Uint8Array>({ pull: () => new Promise(() => {}) });
    const reading = readSse(never, () => {}, controller.signal);
    controller.abort();
    await assert.rejects(reading);
  });
});

describe("HTTP transport", () => {
  it("opens the session with credentials and no-store, then sends the CSRF token on mutations", async () => {
    const calls: { url: string; init: RequestInit }[] = [];
    const fetcher: typeof fetch = async (input, init = {}) => {
      calls.push({ url: String(input), init });
      if (String(input).endsWith("/session")) return json(session);
      return sse(example("stream.recommendation.sse"));
    };
    const transport = createHttpTransport("", fetcher);
    const opened = await transport.openSession(new AbortController().signal);
    assert.equal(opened.messages.length, 0);
    const events: RunEvent[] = [];
    const end = await transport.send(
      { content: "Hola", page: "product", key: "key-000001" },
      new AbortController().signal,
      (e) => events.push(e),
    );
    assert.equal(end, "terminal");
    assert.deepEqual(
      events.map((e) => e.type),
      ["started", "delta", "delta", "delta", "answer", "completed"],
    );
    const [open, send] = calls;
    assert.equal(open?.url, "/api/v1/session");
    assert.equal(open?.init.method, "POST");
    assert.equal(open?.init.credentials, "include");
    assert.equal(open?.init.cache, "no-store");
    const headers = send?.init.headers as Record<string, string>;
    assert.equal(headers["X-CSRF-Token"], "csrf_EXAMPLE_keep_in_memory_only");
    assert.equal(headers["Idempotency-Key"], "key-000001");
    assert.equal(send?.init.body, JSON.stringify({ content: "Hola", page: "product" }));
    assert.ok(!send?.url.includes("csrf"), "credentials never travel in URLs");
  });

  it("maps the API error envelope to typed errors", async () => {
    const transport = createHttpTransport("", async () =>
      json(
        { error: { code: "rate_limited", message: "x", retryable: false, request_id: "r" } },
        429,
      ),
    );
    await assert.rejects(transport.openSession(new AbortController().signal), (error: unknown) => {
      assert.ok(error instanceof AssistantError);
      assert.equal(error.code, "rate_limited");
      return true;
    });
  });

  it("falls back to status mapping for non-JSON errors and marks network failures", async () => {
    const proxy = createHttpTransport(
      "",
      async () => new Response("<html>Bad gateway</html>", { status: 502 }),
    );
    await assert.rejects(proxy.openSession(new AbortController().signal), {
      code: "dependency_unavailable",
    });
    const offline = createHttpTransport("", async () => {
      throw new TypeError("fetch failed");
    });
    await assert.rejects(offline.openSession(new AbortController().signal), { code: "network" });
  });

  it("rejects a malformed session and a non-SSE stream response as protocol errors", async () => {
    const bad = createHttpTransport("", async () => json({ schema_version: "2" }));
    await assert.rejects(bad.openSession(new AbortController().signal), { code: "protocol" });
    const transport = createHttpTransport("", async (input) =>
      String(input).endsWith("/session") ? json(session) : json({ ok: true }),
    );
    await transport.openSession(new AbortController().signal);
    await assert.rejects(
      transport.send(
        { content: "x", page: null, key: "key-000001" },
        new AbortController().signal,
        () => {},
      ),
      { code: "protocol" },
    );
  });
});
